#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Jan 03 21:16:17 CST 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim datapath_sim_behav -key {Behavioral:sim_1:Functional:datapath_sim} -tclbatch datapath_sim.tcl -view /home/napbad/Project/cqu_mips/proj/datapath_sim_behav.wcfg -log simulate.log"
xsim datapath_sim_behav -key {Behavioral:sim_1:Functional:datapath_sim} -tclbatch datapath_sim.tcl -view /home/napbad/Project/cqu_mips/proj/datapath_sim_behav.wcfg -log simulate.log

