# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/napbad/Project/cqu_mips/proj/cqu_mips.srcs/sources_1/ip/ram_easy/ram_easy.xci
# IP: The module: 'ram_easy' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/napbad/Project/cqu_mips/proj/cqu_mips.gen/sources_1/ip/ram_easy/ram_easy_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_easy'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/napbad/Project/cqu_mips/proj/cqu_mips.srcs/sources_1/ip/ram_easy/ram_easy.xci
# IP: The module: 'ram_easy' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/napbad/Project/cqu_mips/proj/cqu_mips.gen/sources_1/ip/ram_easy/ram_easy_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_easy'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
